framework:
    cache:
        # Unique name of your app: used to compute stable namespaces for cache keys.
        #prefix_seed: your_vendor_name/app_name

        # The "app" cache stores to the filesystem by default.
        # The data in this cache should persist between deploys.
        # Other options include:

        # Redis (commented out temporarily to debug memory issue)
        # app: cache.adapter.redis
        # default_redis_provider: '%env(REDIS_URL)%'
        
        # Use filesystem cache temporarily
        app: cache.adapter.filesystem

        # APCu (not recommended for production)
        #app: cache.adapter.apcu

        # Namespaced pools use the above "app" backend by default
        pools:
            cache.global_clearer:
                adapter: cache.adapter.filesystem
                public: true
            doctrine.result_cache_pool:
                adapter: cache.adapter.filesystem
            doctrine.system_cache_pool:
                adapter: cache.adapter.filesystem

